package property;

/**
 * Property record. Each row in `properties` represents a single sale event
 * (the source NSW dataset emits one row per sale, so the same NSW
 * `property_id` may appear multiple times — the API returns the latest by
 * contract_date when there's ambiguity). Fields mirror the most useful
 * columns from that data set so downstream consumers can read address,
 * council, type and most-recent contract date without a join.
 *
 * {@code propertyID} is a 24-character hex string. On the Mongo branch it
 * was a BSON {@code ObjectId}; on this SQLite branch it is the {@code id}
 * TEXT primary key, generated by {@code db.ObjectIdLike} so the API still
 * returns the same wire format.
 */
public class Property {
    public String propertyID;
    public String postcode;
    public String propertyPrice;
    public boolean forSale;
    public String address;
    public String councilName;
    public String propertyType;
    public String contractDate;
    public long searchCount = 0;

    public Property() {}

    public Property(String propertyID, String postcode, String propertyPrice) {
        this.propertyID = propertyID;
        this.postcode = postcode;
        this.propertyPrice = propertyPrice;
        this.forSale = false;
    }
}
